
databases:
  - name: jinx-mongo
    plan: free

services:
  - type: web
    name: bcore
    env: node
    plan: free
    region: singapore
    buildCommand: npm install
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: MONGO_URI
        fromDatabase:
          name: jinx-mongo
          property: connectionString
      - key: VOICE_API
        fromService:
          name: jinx-voice-capsule
          type: web
          property: url
      - key: MASTER_KEY
        sync: false
      - key: CORE_TOKEN
        sync: false

  - type: web
    name: jinx-voice-capsule
    env: node
    plan: free
    region: singapore
    buildCommand: npm install
    startCommand: npm run dev
    envVars:
      - key: PORT
        value: 8080
      - key: VOICES_ROOT
        value: ./data/voices
      - key: COQUI_TTS_URL
        sync: false

  - type: web
    name: adminverse
    env: node
    plan: free
    region: singapore
    buildCommand: npm install
    startCommand: npm run dev
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        fromDatabase:
          name: jinx-mongo
          property: connectionString
